
enum AbilityTargetType {
	NONE = 0,
	
	FRIENDLY = 				1 << 0,
	ENEMY = 				1 << 1,
	
	SEAL = 					1 << 2,
	NON_SEAL = 				1 << 3,
	COIN_PIECE = 			1 << 4,
	FINGER_RING = 			1 << 5,
	FINGER = 				1 << 6,
	
	################################################################################################
	
	ANY = FRIENDLY | ENEMY,
	
	SEAL_FRIENDLY = SEAL | FRIENDLY,
	SEAL_ENEMY = SEAL | ENEMY,
	SEAL_ANY = SEAL | ANY,
	
	NON_SEAL_FRIENDLY = NON_SEAL | FRIENDLY,
	NON_SEAL_ENEMY = NON_SEAL | ENEMY,
	NON_SEAL_ANY = NON_SEAL | ANY,
	
	COIN_PIECE_FRIENDLY = COIN_PIECE | FRIENDLY,
	COIN_PIECE_ENEMY = COIN_PIECE | ENEMY,
	COIN_PIECE_ANY = COIN_PIECE | ANY,
	
	FINGER_RING_FRIENDLY = FINGER_RING | FRIENDLY,
	FINGER_RING_ENEMY = FINGER_RING | ENEMY,
	FINGER_RING_ANY = FINGER_RING | ANY,
	
	FINGER_FRIENDLY = FINGER | FRIENDLY,
	FINGER_ENEMY = FINGER | ENEMY,
	FINGER_ANY = FINGER | ANY,
	
	ALL = Util.INT_MAX,
}
